language: node_js
node_js:
  - 12.4.0

cache:
  directories:
    - node_modules
    - brand

branches:
  only:
    - master
    - gh-pages

script:
  - yarn test --coverage --watchAll=false
  - yarn build
  - [ -e coverage/lcov-report ] && cp -a coverage/lcov-report build/coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_S_KEY
  keep_history: true
  local_dir: build
  on:
    branch: master
