language: node_js
node_js:
  - 12.4.0

cache:
  directories:
    - node_modules
    - brand

branches:
  only:
    - master
    - gh-pages

script:
  - npm run test -- --coverage --watchAll=false
  - npm run build; if[ -e coverage/lcov-report/index.html ] then cp coverage/lcov-report/index.html build/coverage.html; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_S_KEY
  keep_history: true
  local_dir: build
  on:
    branch: master
